/**
 * Hierarchical location database and helper utilities for RoomSync.
 *
 * Country -> States/UTs -> Cities -> Localities & PIN code validation
 */

export const SUPPORTED_COUNTRIES = ["India"] as const;

export type SupportedCountry = (typeof SUPPORTED_COUNTRIES)[number];

export const INDIA_LOCATION_DATA: Record<string, string[]> = {
  // 28 Indian States
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Rajahmundry",
    "Tirupati",
    "Kakinada",
    "Kadapa",
    "Anantapur",
    "Eluru",
    "Vizianagaram",
    "Ongole",
    "Nandyal",
    "Machilipatnam",
    "Tenali",
    "Proddatur",
    "Chittoor",
    "Hindupur",
    "Bhimavaram",
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Tawang",
    "Ziro",
    "Roing",
    "Tezu",
    "Bomdila",
    "Aalo",
  ],
  Assam: [
    "Guwahati",
    "Silchar",
    "Dibrugarh",
    "Jorhat",
    "Nagaon",
    "Tinsukia",
    "Tezpur",
    "Bongaigaon",
    "Diphu",
    "Dhubri",
    "North Lakhimpur",
    "Karimganj",
    "Sivasagar",
    "Goalpara",
  ],
  Bihar: [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Purnia",
    "Darbhanga",
    "Bihar Sharif",
    "Arrah",
    "Begusarai",
    "Katihar",
    "Munger",
    "Chhapra",
    "Saharsa",
    "Sasaram",
    "Hajipur",
    "Dehri",
    "Bettiah",
    "Motihari",
    "Siwan",
    "Kishanganj",
    "Buxar",
    "Jehanabad",
    "Aurangabad (Bihar)",
    "Nawada",
  ],
  Chhattisgarh: [
    "Raipur",
    "Bhilai",
    "Bilaspur",
    "Korba",
    "Durg",
    "Rajnandgaon",
    "Raigarh",
    "Jagdalpur",
    "Ambikapur",
    "Dhamtari",
    "Mahasamund",
  ],
  Goa: [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Curchorem",
    "Cuncolim",
    "Valpoi",
  ],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Anand",
    "Navsari",
    "Morbi",
    "Nadiad",
    "Surendranagar",
    "Bharuch",
    "Mehsana",
    "Bhuj",
    "Porbandar",
    "Vapi",
    "Valsad",
    "Godhra",
    "Palanpur",
    "Veraval",
    "Patan",
    "Dahod",
    "Botad",
    "Amreli",
  ],
  Haryana: [
    "Gurugram",
    "Faridabad",
    "Panipat",
    "Ambala",
    "Yamunanagar",
    "Rohtak",
    "Hisar",
    "Karnal",
    "Sonipat",
    "Panchkula",
    "Sirsa",
    "Bahadurgarh",
    "Jind",
    "Thanesar",
    "Kaithal",
    "Rewari",
    "Palwal",
    "Hansi",
    "Narnaul",
    "Fatehabad",
  ],
  "Himachal Pradesh": [
    "Shimla",
    "Dharamshala",
    "Solan",
    "Mandi",
    "Kullu",
    "Manali",
    "Baddi",
    "Palampur",
    "Bilaspur (HP)",
    "Nahan",
    "Una",
    "Hamirpur",
    "Chamba",
    "Paonta Sahib",
  ],
  Jharkhand: [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro Steel City",
    "Deoghar",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Medininagar",
    "Phusro",
    "Chaibasa",
    "Dumka",
    "Gumia",
    "Ghatshila",
  ],
  Karnataka: [
    "Bengaluru",
    "Mysuru",
    "Hubballi-Dharwad",
    "Mangaluru",
    "Belagavi",
    "Davanagere",
    "Ballari",
    "Vijayapura",
    "Shivamogga",
    "Tumakuru",
    "Kalaburagi",
    "Udupi",
    "Hassan",
    "Bidar",
    "Hosapete",
    "Gadag-Betageri",
    "Chikkamagaluru",
    "Raichur",
    "Bagalkote",
    "Robertsonpet",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Palakkad",
    "Alappuzha",
    "Kannur",
    "Kottayam",
    "Malappuram",
    "Kasaragod",
    "Pathanamthitta",
    "Idukki",
    "Wayanad (Kalpetta)",
  ],
  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Dewas",
    "Satna",
    "Ratlam",
    "Rewa",
    "Katni",
    "Singrauli",
    "Burhanpur",
    "Khandwa",
    "Morena",
    "Bhind",
    "Chhindwara",
    "Guna",
    "Shivpuri",
    "Vidisha",
    "Damoh",
    "Mandsaur",
    "Khargone",
    "Neemuch",
    "Pithampur",
  ],
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Nashik",
    "Kalyan-Dombivli",
    "Vasai-Virar",
    "Navi Mumbai",
    "Chhatrapati Sambhajinagar",
    "Solapur",
    "Mira-Bhayandar",
    "Bhiwandi",
    "Amravati",
    "Nanded",
    "Kolhapur",
    "Akola",
    "Ulhasnagar",
    "Sangli",
    "Malegaon",
    "Jalgaon",
    "Latur",
    "Dhule",
    "Ahmednagar",
    "Chandrapur",
    "Parbhani",
    "Jalna",
    "Panvel",
    "Satara",
    "Ratnagiri",
  ],
  Manipur: [
    "Imphal",
    "Churachandpur",
    "Thoubal",
    "Kakching",
    "Ukhrul",
    "Senapati",
    "Bishnupur",
  ],
  Meghalaya: [
    "Shillong",
    "Tura",
    "Jowai",
    "Nongpoh",
    "Cherrapunji",
    "Williamnagar",
    "Baghmara",
  ],
  Mizoram: [
    "Aizawl",
    "Lunglei",
    "Saiha",
    "Champhai",
    "Kolasib",
    "Serchhip",
    "Lawngtlai",
  ],
  Nagaland: [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Zunheboto",
    "Mon",
    "Phek",
  ],
  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Berhampur",
    "Sambalpur",
    "Puri",
    "Balasore",
    "Bhadrak",
    "Baripada",
    "Jharsuguda",
    "Jeypore",
    "Bargarh",
    "Rayagada",
    "Angul",
  ],
  Punjab: [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali (SAS Nagar)",
    "Hoshiarpur",
    "Batala",
    "Pathankot",
    "Moga",
    "Abohar",
    "Malerkotla",
    "Khanna",
    "Phagwara",
    "Muktsar",
    "Barnala",
    "Firozpur",
    "Kapurthala",
  ],
  Rajasthan: [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Udaipur",
    "Bhilwara",
    "Alwar",
    "Bharatpur",
    "Sri Ganganagar",
    "Sikar",
    "Pali",
    "Chittorgarh",
    "Beawar",
    "Jhunjhunu",
    "Kishangarh",
    "Barmer",
    "Hanumangarh",
    "Tonk",
  ],
  Sikkim: [
    "Gangtok",
    "Namchi",
    "Geyzing",
    "Mangan",
    "Ravangla",
    "Jorethang",
    "Singtam",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tiruppur",
    "Erode",
    "Tirunelveli",
    "Vellore",
    "Thoothukudi",
    "Dindigul",
    "Thanjavur",
    "Ranipet",
    "Sivakasi",
    "Karur",
    "Udhagamandalam (Ooty)",
    "Hosur",
    "Nagercoil",
    "Kanchipuram",
    "Kumarakonam",
    "Cuddalore",
    "Kanyakumari",
  ],
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Ramagundam",
    "Khammam",
    "Mahbubnagar",
    "Nalgonda",
    "Adilabad",
    "Suryapet",
    "Siddipet",
    "Miryalaguda",
    "Mancherial",
    "Jagtial",
  ],
  Tripura: [
    "Agartala",
    "Dharmanagar",
    "Udaipur (Tripura)",
    "Kailashahar",
    "Belonia",
    "Ambassa",
    "Khowai",
  ],
  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Ghaziabad",
    "Agra",
    "Meerut",
    "Varanasi",
    "Prayagraj",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
    "Noida",
    "Greater Noida",
    "Firozabad",
    "Jhansi",
    "Muzaffarnagar",
    "Mathura",
    "Ayodhya",
    "Budaun",
    "Rampur",
    "Shahjahanpur",
    "Farrukhabad",
    "Hapur",
    "Etawah",
    "Mirzapur",
    "Bulandshahr",
    "Sambhal",
    "Amroha",
    "Hardoi",
  ],
  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Roorkee",
    "Haldwani",
    "Rudrapur",
    "Kashipur",
    "Rishikesh",
    "Nainital",
    "Mussoorie",
    "Almora",
    "Pithoragarh",
    "Kotdwar",
    "Tehri",
  ],
  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Durgapur",
    "Asansol",
    "Siliguri",
    "Bardhaman",
    "Malda",
    "Baharampur",
    "Habra",
    "Kharagpur",
    "Shantipur",
    "Dankuni",
    "Dhulian",
    "Ranaghat",
    "Haldia",
    "Darjeeling",
    "Midnapore",
    "Alipurduar",
    "Purulia",
    "Jalpaiguri",
  ],

  // 8 Union Territories
  "Delhi (NCT)": [
    "New Delhi",
    "Central Delhi",
    "North Delhi",
    "South Delhi",
    "East Delhi",
    "West Delhi",
    "North West Delhi",
    "North East Delhi",
    "South West Delhi",
    "South East Delhi",
    "Dwarka",
    "Rohini",
    "Saket",
    "Connaught Place",
    "Karol Bagh",
    "Vasant Kunj",
    "Laxmi Nagar",
    "Janakpuri",
    "Pitampura",
    "Hauz Khas",
    "Mayur Vihar",
  ],
  Chandigarh: ["Chandigarh"],
  "Andaman and Nicobar Islands": [
    "Port Blair",
    "Diglipur",
    "Garacharma",
    "Bambooflat",
  ],
  "Dadra and Nagar Haveli and Daman and Diu": ["Daman", "Diu", "Silvassa"],
  "Jammu and Kashmir": [
    "Srinagar",
    "Jammu",
    "Anantnag",
    "Baramulla",
    "Udhampur",
    "Kathua",
    "Sopore",
    "Rajouri",
    "Punch",
    "Kupwara",
  ],
  Ladakh: ["Leh", "Kargil"],
  Lakshadweep: ["Kavaratti", "Agatti", "Andrott", "Minicoy", "Amini"],
  Puducherry: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
};

export const COMMON_LOCALITIES: Record<string, string[]> = {
  Bengaluru: [
    "Koramangala",
    "HSR Layout",
    "Indiranagar",
    "BTM Layout",
    "Whitefield",
    "Electronic City",
    "Jayanagar",
    "Marathahalli",
    "Bellandur",
    "Malleshwaram",
    "JP Nagar",
    "Hebbal",
    "Banashankari",
    "Yelahanka",
    "Sarjapur Road",
    "Rajajinagar",
    "Bannerghatta Road",
  ],
  Mumbai: [
    "Andheri West",
    "Andheri East",
    "Bandra West",
    "Bandra East",
    "Powai",
    "Juhu",
    "Goregaon West",
    "Goregaon East",
    "Borivali West",
    "Borivali East",
    "Dadar",
    "Malad West",
    "Malad East",
    "Kandivali West",
    "Kandivali East",
    "Santacruz",
    "Lower Parel",
    "Kurla",
    "Chembur",
    "Ghatkopar",
  ],
  "Navi Mumbai": [
    "Vashi",
    "Nerul",
    "Belapur",
    "Kharghar",
    "Seawoods",
    "Kopar Khairane",
    "Airoli",
    "Panvel",
  ],
  Thane: [
    "Ghodbunder Road",
    "Naupada",
    "Majiwada",
    "Panchpakhadi",
    "Vartak Nagar",
    "Wagle Estate",
  ],
  Pune: [
    "Kothrud",
    "Viman Nagar",
    "Hinjawadi",
    "Baner",
    "Wakad",
    "Aundh",
    "Koregaon Park",
    "Hadapsar",
    "Magarpatta",
    "Shivaji Nagar",
    "Pimple Saudagar",
    "Kalyani Nagar",
    "Bavdhan",
    "Kharadi",
  ],
  Hyderabad: [
    "Hitec City",
    "Gachibowli",
    "Madhapur",
    "Kondapur",
    "Banjara Hills",
    "Jubilee Hills",
    "Kukatpally",
    "Secunderabad",
    "Ameerpet",
    "Manikonda",
    "Begumpet",
    "Miyapur",
  ],
  Chennai: [
    "Adyar",
    "Velachery",
    "T Nagar",
    "Anna Nagar",
    "OMR (Old Mahabalipuram Rd)",
    "Thiruvanmiyur",
    "Nungambakkam",
    "Guindy",
    "Besant Nagar",
    "Mylapore",
    "Porur",
    "Perungudi",
  ],
  Kolkata: [
    "Salt Lake (Bidhannagar)",
    "New Town",
    "Park Street",
    "Ballygunge",
    "Behala",
    "Dum Dum",
    "Garia",
    "Jadavpur",
    "Shyambazar",
    "Alipore",
    "Howrah",
  ],
  "New Delhi": [
    "Connaught Place",
    "Hauz Khas",
    "Saket",
    "Vasant Kunj",
    "Karol Bagh",
    "Laxmi Nagar",
    "Dwarka",
    "Rohini",
    "Janakpuri",
    "Pitampura",
    "Mayur Vihar",
    "Greater Kailash",
    "South Extension",
  ],
  Gurugram: [
    "Cyber City",
    "Sector 14",
    "Sector 29",
    "Sector 43",
    "Sector 45",
    "Sector 56",
    "Golf Course Road",
    "Sohna Road",
    "DLF Phase 1",
    "DLF Phase 2",
    "DLF Phase 3",
  ],
  Noida: [
    "Sector 18",
    "Sector 62",
    "Sector 15",
    "Sector 50",
    "Sector 76",
    "Sector 128",
    "Sector 137",
    "Sector 150",
  ],
  Jaipur: [
    "Malviya Nagar",
    "Vaishali Nagar",
    "Mansarovar",
    "C Scheme",
    "Raja Park",
    "Jagatpura",
    "Tonk Road",
  ],
  Ahmedabad: [
    "Navrangpura",
    "Satellite",
    "Bodakdev",
    "Vastrapur",
    "Prahlad Nagar",
    "Maninagar",
    "SG Highway",
    "Thaltej",
  ],
  Patna: [
    "Boring Road",
    "Kankarbagh",
    "Bailey Road",
    "Rajendra Nagar",
    "Patliputra Colony",
    "Ashiana Nagar",
    "Danapur",
    "Fraser Road",
  ],
};

export const STATE_PIN_PREFIX_MAP: Record<string, string[]> = {
  "Delhi (NCT)": ["1"],
  Haryana: ["1"],
  Punjab: ["1"],
  "Himachal Pradesh": ["1"],
  "Jammu and Kashmir": ["1"],
  Ladakh: ["1"],
  Chandigarh: ["1"],
  "Uttar Pradesh": ["2"],
  Uttarakhand: ["2"],
  Rajasthan: ["3"],
  Gujarat: ["3"],
  "Dadra and Nagar Haveli and Daman and Diu": ["3"],
  Maharashtra: ["4"],
  Goa: ["4"],
  "Madhya Pradesh": ["4"],
  Chhattisgarh: ["4"],
  "Andhra Pradesh": ["5"],
  Telangana: ["5"],
  Karnataka: ["5"],
  "Tamil Nadu": ["6"],
  Kerala: ["6"],
  Puducherry: ["6"],
  Lakshadweep: ["6"],
  "West Bengal": ["7"],
  Odisha: ["7"],
  "Arunachal Pradesh": ["7"],
  Assam: ["7"],
  Manipur: ["7"],
  Meghalaya: ["7"],
  Mizoram: ["7"],
  Nagaland: ["7"],
  Tripura: ["7"],
  Sikkim: ["7"],
  "Andaman and Nicobar Islands": ["7"],
  Bihar: ["8"],
  Jharkhand: ["8"],
};

export function getStatesForCountry(country: string): string[] {
  if (!country || country.trim().toLowerCase() !== "india") {
    return [];
  }
  return Object.keys(INDIA_LOCATION_DATA);
}

export function getCitiesForState(country: string, state: string): string[] {
  if (!country || country.trim().toLowerCase() !== "india" || !state) {
    return [];
  }
  const cleanState = state.split("(")[0].trim().toLowerCase();
  for (const [sName, cities] of Object.entries(INDIA_LOCATION_DATA)) {
    if (
      sName.toLowerCase() === state.trim().toLowerCase() ||
      sName.split("(")[0].trim().toLowerCase() === cleanState
    ) {
      return cities;
    }
  }
  return [];
}

export function getLocalitiesForCity(city: string): string[] {
  if (!city) return [];
  const cleanCity = city.split("(")[0].trim().toLowerCase();
  for (const [cName, localities] of Object.entries(COMMON_LOCALITIES)) {
    if (
      cName.toLowerCase() === city.trim().toLowerCase() ||
      cName.split("(")[0].trim().toLowerCase() === cleanCity
    ) {
      return localities;
    }
  }
  return [];
}

export function isValidCountry(country: string): boolean {
  return (
    SUPPORTED_COUNTRIES.some(
      (c) => c.toLowerCase() === country?.trim().toLowerCase()
    )
  );
}

export function isValidState(country: string, state: string): boolean {
  const states = getStatesForCountry(country);
  const cleanState = state?.split("(")[0].trim().toLowerCase();
  return states.some(
    (s) =>
      s.toLowerCase() === state?.trim().toLowerCase() ||
      s.split("(")[0].trim().toLowerCase() === cleanState
  );
}

export function isValidCity(
  country: string,
  state: string,
  city: string
): boolean {
  const cities = getCitiesForState(country, state);
  const cleanCity = city?.split("(")[0].trim().toLowerCase();
  return cities.some(
    (c) =>
      c.toLowerCase() === city?.trim().toLowerCase() ||
      c.split("(")[0].trim().toLowerCase() === cleanCity
  );
}

export function findStateForCity(country: string, city: string): string[] {
  if (!country || country.trim().toLowerCase() !== "india" || !city) return [];
  const cleanCity = city.split("(")[0].trim().toLowerCase();
  const matching: string[] = [];

  for (const [sName, cities] of Object.entries(INDIA_LOCATION_DATA)) {
    if (
      cities.some(
        (c) =>
          c.toLowerCase() === city.trim().toLowerCase() ||
          c.split("(")[0].trim().toLowerCase() === cleanCity
      )
    ) {
      matching.push(sName);
    }
  }
  return matching;
}

export function validatePincodeForState(
  state: string,
  pincode: string
): { isValid: boolean; error?: string } {
  const cleanPin = pincode.trim();
  if (!/^\d{6}$/.test(cleanPin)) {
    return {
      isValid: false,
      error: "PIN code must contain exactly 6 digits.",
    };
  }

  const cleanState = state.split("(")[0].trim().toLowerCase();
  for (const [sName, prefixes] of Object.entries(STATE_PIN_PREFIX_MAP)) {
    if (
      sName.toLowerCase() === state.trim().toLowerCase() ||
      sName.split("(")[0].trim().toLowerCase() === cleanState
    ) {
      if (!prefixes.some((p) => cleanPin.startsWith(p))) {
        const expected = prefixes.join("/");
        return {
          isValid: false,
          error: `PIN code for ${sName} must begin with ${expected} (e.g. ${expected}xxxxx).`,
        };
      }
      return { isValid: true };
    }
  }

  return { isValid: true };
}
