"""Add client_id to Message

Revision ID: 198cb74c4fe0
Revises: f9a215ad9239
Create Date: 2026-08-31 14:55:19.569417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198cb74c4fe0'
down_revision: Union[str, Sequence[str], None] = 'f9a215ad9239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'messages', ['client_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_column('messages', 'client_id')
    # ### end Alembic commands ###
