"""add_ml_features_to_lifestyle_profiles

Revision ID: bc2e7e6ae7be
Revises: c3d4e5f6a7b8
Create Date: 2026-08-23 16:28:42.611331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2e7e6ae7be'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lifestyle_profiles', sa.Column('schedule_consistency', sa.Integer(), server_default='3', nullable=False))
    op.add_column('lifestyle_profiles', sa.Column('study_hours', sa.Integer(), server_default='3', nullable=False))
    op.add_column('lifestyle_profiles', sa.Column('noise_sleep_tolerance', sa.Integer(), server_default='3', nullable=False))
    op.add_column('lifestyle_profiles', sa.Column('cleanliness_score', sa.Integer(), server_default='3', nullable=False))
    op.add_column('lifestyle_profiles', sa.Column('privacy_preference', sa.Integer(), server_default='3', nullable=False))
    op.add_column('lifestyle_profiles', sa.Column('talkativeness', sa.Integer(), server_default='3', nullable=False))
    op.add_column('lifestyle_profiles', sa.Column('friendship_expectation', sa.Integer(), server_default='3', nullable=False))
    op.add_column('lifestyle_profiles', sa.Column('gaming_hours', sa.Integer(), server_default='0', nullable=False))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('lifestyle_profiles', 'gaming_hours')
    op.drop_column('lifestyle_profiles', 'friendship_expectation')
    op.drop_column('lifestyle_profiles', 'talkativeness')
    op.drop_column('lifestyle_profiles', 'privacy_preference')
    op.drop_column('lifestyle_profiles', 'cleanliness_score')
    op.drop_column('lifestyle_profiles', 'noise_sleep_tolerance')
    op.drop_column('lifestyle_profiles', 'study_hours')
    op.drop_column('lifestyle_profiles', 'schedule_consistency')
    # ### end Alembic commands ###
