"""add session id to refresh tokens

Revision ID: bf735c6a7e48
Revises: 5852a4bc105d
Create Date: 2026-07-31 16:21:19.845254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf735c6a7e48'
down_revision: Union[str, Sequence[str], None] = '5852a4bc105d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_unique_constraint(None, 'refresh_tokens', ['session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_column('refresh_tokens', 'session_id')
    # ### end Alembic commands ###
