"""add is_revoked to refresh tokens

Revision ID: f870b79c85bc
Revises: bf735c6a7e48
Create Date: 2026-07-31 17:12:13.060934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f870b79c85bc'
down_revision: Union[str, Sequence[str], None] = 'bf735c6a7e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint(op.f('refresh_tokens_session_id_key'), 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.create_unique_constraint(op.f('refresh_tokens_session_id_key'), 'refresh_tokens', ['session_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('refresh_tokens', 'is_revoked')
    # ### end Alembic commands ###
